CREATE TABLE endpoints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    hostname VARCHAR(255) NOT NULL,
    device_name VARCHAR(255) NOT NULL,
    operating_system VARCHAR(255) NOT NULL,
    platform VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,
    demo_data BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT endpoint_status_check CHECK (status IN ('ONLINE', 'OFFLINE', 'UNKNOWN')),
    CONSTRAINT endpoint_user_hostname_unique UNIQUE (user_id, hostname)
);
CREATE INDEX idx_endpoints_user_last_seen ON endpoints(user_id, last_seen_at DESC);

CREATE TABLE endpoint_security_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint_id BIGINT NOT NULL REFERENCES endpoints(id) ON DELETE CASCADE,
    event_type VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    source VARCHAR(255) NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    suspicious BOOLEAN NOT NULL,
    demo_data BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT endpoint_event_severity_check CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'))
);
CREATE INDEX idx_endpoint_events_endpoint_observed ON endpoint_security_events(endpoint_id, observed_at DESC);
CREATE INDEX idx_endpoint_events_suspicious ON endpoint_security_events(endpoint_id, suspicious);
