ALTER TABLE scans DROP CONSTRAINT IF EXISTS scans_status_check;
ALTER TABLE scans ADD CONSTRAINT scans_status_check CHECK (status IN ('PENDING','UPLOADED','QUEUED','RUNNING','COMPLETED','FAILED','CANCELLED'));
CREATE TABLE apk_analyses (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 scan_id BIGINT NOT NULL UNIQUE REFERENCES scans(id),
 package_name VARCHAR(255), application_name VARCHAR(255), version_name VARCHAR(255), version_code VARCHAR(255),
 min_sdk VARCHAR(255), target_sdk VARCHAR(255), sha256 VARCHAR(64) NOT NULL, md5 VARCHAR(32) NOT NULL,
 file_size BIGINT NOT NULL, storage_key VARCHAR(255) NOT NULL, analysis_mode VARCHAR(255),
 stage VARCHAR(255) NOT NULL, progress INTEGER NOT NULL, message VARCHAR(1000),
 jadx_status VARCHAR(255), apktool_status VARCHAR(255), aapt_status VARCHAR(255),
 started_at TIMESTAMP WITH TIME ZONE, completed_at TIMESTAMP WITH TIME ZONE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL, source_summary TEXT NOT NULL, artifacts_retained BOOLEAN NOT NULL
);
CREATE TABLE permission_findings (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, apk_analysis_id BIGINT NOT NULL REFERENCES apk_analyses(id),
 permission_name VARCHAR(512), category VARCHAR(255), severity VARCHAR(255), description VARCHAR(2000)
);
CREATE TABLE component_findings (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, apk_analysis_id BIGINT NOT NULL REFERENCES apk_analyses(id),
 component_type VARCHAR(255), component_name VARCHAR(512), exported BOOLEAN, permission VARCHAR(512), severity VARCHAR(255)
);
CREATE TABLE api_findings (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, apk_analysis_id BIGINT NOT NULL REFERENCES apk_analyses(id),
 class_name VARCHAR(512), method_name VARCHAR(512), api_name VARCHAR(255), category VARCHAR(255), severity VARCHAR(255), description VARCHAR(2000)
);
CREATE TABLE extracted_strings (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, apk_analysis_id BIGINT NOT NULL REFERENCES apk_analyses(id),
 text_value VARCHAR(2000), kind VARCHAR(255), source VARCHAR(512)
);
CREATE INDEX idx_permissions_analysis ON permission_findings(apk_analysis_id);
CREATE INDEX idx_components_analysis ON component_findings(apk_analysis_id);
CREATE INDEX idx_apis_analysis ON api_findings(apk_analysis_id);
CREATE INDEX idx_strings_analysis ON extracted_strings(apk_analysis_id);
