CREATE TABLE threat_intelligence_source (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 description VARCHAR(1000),
 source_type VARCHAR(20) NOT NULL CHECK (source_type IN ('LOCAL','IMPORTED','MANUAL')),
 url VARCHAR(500),
 enabled BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE threat_intelligence (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 indicator VARCHAR(2000) NOT NULL,
 indicator_type VARCHAR(50) NOT NULL CHECK (indicator_type IN ('URL','DOMAIN','IP','HASH','PACKAGE','API','STRING')),
 threat_name VARCHAR(255),
 threat_family VARCHAR(255),
 category VARCHAR(50),
 severity VARCHAR(20) NOT NULL CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
 confidence VARCHAR(20) NOT NULL CHECK (confidence IN ('LOW','MEDIUM','HIGH')),
 description VARCHAR(4000),
 source VARCHAR(50),
 tags VARCHAR(1000),
 first_seen TIMESTAMP WITH TIME ZONE,
 last_seen TIMESTAMP WITH TIME ZONE,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_threat_intel_indicator ON threat_intelligence(indicator);
CREATE INDEX idx_threat_intel_type ON threat_intelligence(indicator_type);
CREATE INDEX idx_threat_intel_category ON threat_intelligence(category);
CREATE INDEX idx_threat_intel_severity ON threat_intelligence(severity);
CREATE INDEX idx_threat_intel_active ON threat_intelligence(active);
CREATE INDEX idx_threat_intel_source ON threat_intelligence(source);

CREATE TABLE threat_match (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 ioc_id BIGINT NOT NULL REFERENCES iocs(id),
 threat_intelligence_id BIGINT NOT NULL REFERENCES threat_intelligence(id),
 match_type VARCHAR(20) NOT NULL CHECK (match_type IN ('EXACT','PARTIAL','PATTERN')),
 status VARCHAR(20) NOT NULL CHECK (status IN ('MATCHED','NO_MATCH','REVIEW')),
 confidence VARCHAR(20) NOT NULL CHECK (confidence IN ('LOW','MEDIUM','HIGH')),
 severity VARCHAR(20) NOT NULL CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
 matched_at TIMESTAMP WITH TIME ZONE NOT NULL,
 description VARCHAR(4000)
);
CREATE INDEX idx_threat_match_ioc ON threat_match(ioc_id);
CREATE INDEX idx_threat_match_ti ON threat_match(threat_intelligence_id);
CREATE INDEX idx_threat_match_status ON threat_match(status);