CREATE TABLE risk_assessment (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 scan_id BIGINT NOT NULL REFERENCES scans(id),
 apk_analysis_id BIGINT NOT NULL REFERENCES apk_analyses(id),
 score NUMERIC(5,2) NOT NULL CHECK (score >= 0 AND score <= 100),
 risk_level VARCHAR(20) NOT NULL CHECK (risk_level IN ('LOW','MEDIUM','HIGH','CRITICAL')),
 confidence VARCHAR(20) NOT NULL CHECK (confidence IN ('LOW','MEDIUM','HIGH')),
 summary VARCHAR(4000),
 is_latest BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_risk_assessment_scan ON risk_assessment(scan_id);
CREATE INDEX idx_risk_assessment_analysis ON risk_assessment(apk_analysis_id);
CREATE INDEX idx_risk_assessment_latest ON risk_assessment(is_latest);
CREATE INDEX idx_risk_assessment_risk_level ON risk_assessment(risk_level);

CREATE TABLE risk_indicator (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 risk_assessment_id BIGINT NOT NULL REFERENCES risk_assessment(id) ON DELETE CASCADE,
 source_type VARCHAR(50) NOT NULL CHECK (source_type IN ('PERMISSION','API','STATIC_FINDING','IOC','THREAT_INTELLIGENCE','URL','DOMAIN','IP','COMPONENT','OBFUSCATION','NATIVE_LIBRARY')),
 source_id BIGINT,
 category VARCHAR(50) NOT NULL,
 description VARCHAR(1000),
 severity VARCHAR(20) NOT NULL CHECK (severity IN ('LOW','MEDIUM','HIGH','CRITICAL')),
 confidence VARCHAR(20) NOT NULL CHECK (confidence IN ('LOW','MEDIUM','HIGH')),
 contribution NUMERIC(5,2) NOT NULL CHECK (contribution >= 0),
 evidence VARCHAR(4000),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_risk_indicator_assessment ON risk_indicator(risk_assessment_id);
CREATE INDEX idx_risk_indicator_category ON risk_indicator(category);
CREATE INDEX idx_risk_indicator_severity ON risk_indicator(severity);
CREATE INDEX idx_risk_indicator_source_type ON risk_indicator(source_type);