import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, BarChart, Bar } from 'recharts';
import { ArrowUpRight, ArrowRight, PackageSearch, ShieldAlert, Link as LinkIcon, Fingerprint, Bell, Gauge, CalendarDays, ChevronDown, Radio, Shield, Link2 } from 'lucide-react';
import { Card, Badge, Table, Loading, ErrorState, Modal } from '../components/ui';
import { getDashboardStats, getThreatTrends, getRecentEvents, getDistributions } from '../api/dashboardApi';
const icons = { apk: PackageSearch, shield: ShieldAlert, link: LinkIcon, ioc: Fingerprint, alert: Bell, risk: Gauge, intel: Shield, correlation: Link2 };
const tooltip = { background: '#152236', border: '1px solid #304158', borderRadius: 8, color: '#e9f0fb', fontSize: 12 };
export const eventColumns = [{ key: 'event', label: 'SECURITY EVENT', render: r => <div className="event-cell"><span className={`event-dot ${r.severity.toLowerCase()}`} /><span>{r.event}<small>{r.id}</small></span></div> }, { key: 'type', label: 'TYPE' }, { key: 'severity', label: 'SEVERITY', render: r => <Badge>{r.severity}</Badge> }, { key: 'source', label: 'SOURCE', render: r => <span className="mono source">{r.source}</span> }, { key: 'time', label: 'TIME' }, { key: 'status', label: 'STATUS', render: r => <span className={`status-text ${r.status.toLowerCase()}`}>{r.status}</span> }];
export function EventModal({ event, close }) { return <Modal title={event.event} onClose={close}><div className="modal-body"><div className="detail-line"><span>Severity</span><Badge>{event.severity}</Badge></div><div className="detail-line"><span>Event ID</span><span className="mono">{event.id}</span></div><div className="detail-line"><span>Source</span><span className="mono">{event.source}</span></div><p>{event.description}</p><div className="info-note">Sample event for interface demonstration. No analysis has been performed.</div></div></Modal>; }
export default function Dashboard() {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [days, setDays] = useState('7'); const [selected, setSelected] = useState(null); const [attempt, setAttempt] = useState(0);
  useEffect(() => { let active = true; Promise.all([getDashboardStats(), getThreatTrends(days), getRecentEvents(), getDistributions()]).then(([stats, trends, events, distributions]) => { if (active) setData({ stats, trends, events, ...distributions }); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [days, attempt]);
  if (error) return <ErrorState message={error} retry={() => { setError(''); setAttempt(a => a + 1); }} />;
  if (!data) return <Loading />;
  return <><div className="page-heading"><div><div className="eyebrow">SECURITY OPERATIONS CENTER</div><h1>Threat overview<span className="title-dot">.</span></h1><p>A clear view of your threat landscape. Every signal, in context.</p></div><div className="heading-actions"><label className="range-select"><CalendarDays size={16} /><select aria-label="Dashboard time period" value={days} onChange={e => setDays(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option></select><ChevronDown size={14} /></label><Link to="/apk-analysis" className="button primary"><PackageSearch size={17} />New analysis<ArrowUpRight size={16} /></Link></div></div>
    <div className="sample-banner"><Radio size={15} /><strong>Sample intelligence</strong><span>Explore the foundation with illustrative data. Analysis integrations are not connected.</span><Badge tone="neutral">DEMO DATA</Badge></div>
    <div className="stats-grid">{data.stats.map(s => { const Icon = icons[s.icon]; return <Card key={s.label} className={`stat-card ${s.tone}`}><div className="stat-label">{s.label}<span className="stat-icon"><Icon size={18} /></span></div><div className="stat-value">{s.value}<small>{s.suffix}</small></div><div className="stat-bottom"><span className={`stat-change ${s.tone}`}>{s.change.includes('%') && <ArrowUpRight size={12} />}{s.change}</span><span>{s.detail}</span></div></Card>; })}</div>
    <div className="charts-top"><Card className="trend-panel"><div className="panel-heading"><div><h2>Threat detection trend</h2><p>Malicious and suspicious signals over time</p></div><div className="chart-legend"><span><i className="teal-bg" />Suspicious</span><span><i className="red-bg" />Malicious</span></div></div><div className="trend-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.trends} margin={{ top: 12, right: 15, left: -26, bottom: 0 }}><defs><linearGradient id="teal-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#35c9b2" stopOpacity={0.22} /><stop offset="100%" stopColor="#35c9b2" stopOpacity={0} /></linearGradient><linearGradient id="red-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ee6c82" stopOpacity={0.15} /><stop offset="100%" stopColor="#ee6c82" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#243045" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: '#91a0b8', fontSize: 11 }} dy={10} /><YAxis axisLine={false} tickLine={false} tick={{ fill: '#91a0b8', fontSize: 11 }} /><Tooltip contentStyle={tooltip} /><Area type="monotone" dataKey="suspicious" name="Suspicious" stroke="#39d0b7" strokeWidth={2.3} fill="url(#teal-fill)" /><Area type="monotone" dataKey="malicious" name="Malicious" stroke="#ee6c82" strokeWidth={2} fill="url(#red-fill)" /></AreaChart></ResponsiveContainer></div><div className="chart-foot"><span><i className="status-dot" />Sample detection activity</span><span>{days === '7' ? 'Weekly' : 'Monthly'} overview</span></div></Card>
    <Card className="risk-panel"><div className="panel-heading"><div><h2>Risk distribution</h2><p>Sample findings by severity</p></div><Gauge size={18} className="muted" /></div><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.risk} dataKey="value" innerRadius={66} outerRadius={86} paddingAngle={5} stroke="none" startAngle={90} endAngle={-270}>{data.risk.map(r => <Cell key={r.name} fill={r.color} />)}</Pie><Tooltip contentStyle={tooltip} /></PieChart></ResponsiveContainer><div className="donut-center"><strong>100</strong><span>FINDINGS</span></div></div><div className="risk-legend">{data.risk.map(r => <div key={r.name}><span><i style={{ background: r.color }} />{r.name}</span><strong>{r.value}<small>%</small></strong></div>)}</div></Card></div>
    <div className="lower-grid"><Card className="events-panel"><div className="panel-heading"><div><h2>Recent security events <span className="count-label">5</span></h2><p>Latest signals requiring your attention</p></div><Link className="text-link" to="/scan-history">View all events<ArrowRight size={15} /></Link></div><Table columns={eventColumns} rows={data.events} onRowClick={setSelected} /></Card><Card className="types-panel"><div className="panel-heading"><div><h2>Threat types</h2><p>Distribution by category</p></div></div><div className="types-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.types} layout="vertical" margin={{ left: 0, right: 24 }}><XAxis type="number" hide /><YAxis dataKey="name" type="category" axisLine={false} tickLine={false} width={65} tick={{ fill: '#a8b6cb', fontSize: 11 }} /><Tooltip contentStyle={tooltip} cursor={{ fill: '#ffffff05' }} /><Bar dataKey="value" name="Findings" radius={[0, 3, 3, 0]} barSize={12}>{data.types.map((t, i) => <Cell key={t.name} fill={['#39d0b7', '#5d9bf5', '#b397ee', '#f2b45c'][i]} />)}</Bar></BarChart></ResponsiveContainer></div><div className="type-total"><strong>220</strong><span>classified sample threats</span></div></Card></div>{selected && <EventModal event={selected} close={() => setSelected(null)} />}</>;
}
