import { useEffect, useState } from 'react';
import { UploadCloud, ShieldCheck, ArrowRight, Search, Download, Check, Server, CircleHelp, FileCode, LockKeyhole } from 'lucide-react';
import { Card, Badge, Button, Table, Loading, ErrorState } from '../components/ui';
import { getRecentEvents } from '../api/dashboardApi';
import api from '../api/axios';
import { validateApk } from '../api/scanApi';
import { eventColumns, EventModal } from './Dashboard';
import { useAuth } from '../hooks/useAuth';
import ThreatIntelligencePage from './ThreatIntelligence';
import RiskCorrelationPage from './RiskCorrelation';
import AlertsPage from './Alerts';
import ScanHistoryPage from './ScanHistory';
import ReportsPage from './Reports';
const descriptions = { '/apk-analysis': 'Inspect Android packages through a static-first analysis workflow.', '/url-scanner': 'Inspect URLs for suspicious infrastructure and malicious signals.', '/phishing': 'Identify deceptive pages and credential-harvesting patterns.', '/threat-intelligence': 'Bring context to threats with connected intelligence sources.', '/ioc-explorer': 'Explore indicators and follow the evidence across your investigations.', '/risk-correlation': 'Connect isolated findings into a clearer picture of risk.', '/scan-history': 'Review recent investigations and their security findings.', '/reports': 'Turn technical findings into actionable intelligence.', '/alerts': 'Prioritize the signals that need your attention.', '/endpoint-monitoring': 'Understand endpoint coverage and security posture.', '/settings': 'Manage your workspace preferences and connection details.' };
export default function ModulePage({ module }) {
  const { path, label, icon: Icon } = module;
  return <><div className="page-heading"><div><div className="eyebrow">{['/settings', '/endpoint-monitoring'].includes(path) ? 'WORKSPACE MANAGEMENT' : 'SECURITY WORKSPACE'}</div><h1>{label}<span className="title-dot">.</span></h1><p>{descriptions[path]}</p></div><span className="page-icon"><Icon size={27} /></span></div>{['/url-scanner', '/phishing', '/ioc-explorer', '/endpoint-monitoring'].includes(path) && <div className="sample-banner"><CircleHelp size={16} /><strong>Foundation preview</strong><span>Illustrative data only. Live analysis and intelligence integrations are planned.</span><Badge tone="neutral">STEP 01</Badge></div>}{path === '/apk-analysis' ? <ApkPage /> : ['/url-scanner', '/phishing'].includes(path) ? <UrlPage phishing={path === '/phishing'} /> : path === '/scan-history' ? <ScanHistoryPage /> : path === '/alerts' ? <AlertsPage /> : path === '/ioc-explorer' ? <IocPage /> : path === '/threat-intelligence' ? <ThreatIntelligencePage /> : path === '/risk-correlation' ? <RiskCorrelationPage scanId={null} /> : path === '/reports' ? <ReportsPage /> : path === '/endpoint-monitoring' ? <EndpointsPage /> : <SettingsPage />}</>;
}
function ApkPage() {
  const [file, setFile] = useState(null); const [error, setError] = useState('');
  function choose(candidate) { const issue = validateApk(candidate); setError(issue || ''); setFile(issue ? null : candidate); }
  return <div className="module-grid"><Card className="padded"><h2>Start an APK investigation</h2><p className="muted">Select a package to check its local file requirements.</p><label className="upload-zone" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); choose(e.dataTransfer.files[0]); }}><UploadCloud size={38} /><strong>{file ? file.name : 'Drop an APK file here'}</strong><span>{file ? `${(file.size / 1024 / 1024).toFixed(2)} MB · Ready for a future upload` : 'or browse from your computer'}</span><small>.apk files only · Maximum 50 MB</small><input type="file" accept=".apk" aria-label="Choose APK file" onChange={e => choose(e.target.files[0])} /></label>{error && <div className="form-error" role="alert">{error}</div>}{file && <div className="success-note"><Check size={17} />Filename and size checks passed. The file remains on your device; content validation will be performed by the future backend.</div>}<Button disabled><LockKeyhole size={16} />Analysis available in Step 2</Button><p className="small muted">No files are uploaded or executed in this foundation.</p></Card><Card className="padded"><h2>Static analysis pipeline</h2><p className="muted">Designed to inspect code without running it.</p><div className="pipeline">{[['01', 'Validate & fingerprint', 'File signature, limits, and SHA-256 hash'], ['02', 'Decode & decompile', 'JADX, Apktool, and aapt'], ['03', 'Extract security signals', 'Androguard and YARA rules'], ['04', 'Correlate & report', 'IOCs, risk scoring, alerts, and reports']].map(([n, title, text]) => <div key={n}><span>{n}</span><section><h3>{title}</h3><p>{text}</p></section></div>)}</div><div className="info-note"><ShieldCheck size={20} />APK files are analyzed statically and are never executed.</div></Card></div>;
}
function UrlPage({ phishing }) {
  const [url, setUrl] = useState(''); const [message, setMessage] = useState(''); const [valid, setValid] = useState(false);
  function check(e) { e.preventDefault(); try { const parsed = new URL(url); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error(); setValid(true); setMessage('URL format is valid. The scanning service is planned; this address has not been visited or analyzed.'); } catch { setValid(false); setMessage('Enter a complete HTTP or HTTPS URL, such as https://example.com.'); } }
  return <><Card className="padded scanner-card"><span className="page-icon"><ShieldCheck size={29} /></span><h2>{phishing ? 'Inspect a suspected phishing URL' : 'Investigate a suspicious URL'}</h2><p className="muted">{phishing ? 'Prepare an address for future brand impersonation and credential-form checks.' : 'Prepare an address for future reputation and infrastructure checks.'}</p><form onSubmit={check}><label htmlFor="target-url">Target URL</label><div className="inline-form"><input id="target-url" placeholder="https://example.com" value={url} onChange={e => { setUrl(e.target.value); setMessage(''); }} required /><Button type="submit">Check format<ArrowRight size={16} /></Button></div></form>{message && <div role="status" className={valid ? 'info-note' : 'form-error'}>{message}</div>}</Card><div className="feature-row">{(phishing ? [['Brand impersonation', 'Identify deceptive branding and domain similarities.'], ['Credential forms', 'Inspect suspicious authentication requests.'], ['Content signals', 'Combine page patterns with infrastructure context.']] : [['URL reputation', 'Correlate addresses with intelligence providers.'], ['Domain context', 'Inspect domain age and hosting information.'], ['IOC matching', 'Match extracted indicators against known signals.']]).map(([title, text]) => <Card className="padded" key={title}><Badge tone="neutral">PLANNED</Badge><h3>{title}</h3><p>{text}</p></Card>)}</div></>;
}
function EventsPage({ alerts }) {
  const [rows, setRows] = useState(null); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [severity, setSeverity] = useState('All severities'); const [selected, setSelected] = useState(null);
  useEffect(() => { getRecentEvents().then(setRows).catch(e => setError(e.message)); }, []);
  if (error) return <ErrorState message={error} />; if (!rows) return <Loading />;
  const visible = rows.filter(r => (!alerts || ['Open', 'Investigating'].includes(r.status)) && (severity === 'All severities' || r.severity === severity) && `${r.event} ${r.source} ${r.type}`.toLowerCase().includes(query.toLowerCase()));
  return <Card><div className="panel-heading"><div><h2>{alerts ? 'Alert queue' : 'Investigation history'}</h2><p>{visible.length} sample {alerts ? 'alerts' : 'events'}</p></div><Badge tone="neutral">SAMPLE DATA</Badge></div><div className="filterbar"><div className="filter-input"><Search size={16} /><input aria-label="Filter events" placeholder="Search events or sources…" value={query} onChange={e => setQuery(e.target.value)} /></div><select aria-label="Filter severity" value={severity} onChange={e => setSeverity(e.target.value)}>{['All severities', 'Critical', 'High', 'Medium', 'Low'].map(s => <option key={s}>{s}</option>)}</select></div><Table columns={eventColumns} rows={visible} onRowClick={setSelected} />{selected && <EventModal event={selected} close={() => setSelected(null)} />}</Card>;
}
const indicators = [{ id: 1, value: '198.51.100.24', type: 'IPv4', risk: 'High', source: 'Sample APK', matches: '3 findings' }, { id: 2, value: 'account-verify.example', type: 'Domain', risk: 'Critical', source: 'Sample phishing report', matches: '5 findings' }, { id: 3, value: 'telemetry.example', type: 'Domain', risk: 'Low', source: 'Sample intelligence feed', matches: '1 finding' }, { id: 4, value: 'https://download.example/update', type: 'URL', risk: 'Medium', source: 'Sample manifest', matches: '2 findings' }];
function IocPage() { const [query, setQuery] = useState(''); const [type, setType] = useState('All types'); return <Card><div className="panel-heading"><div><h2>Indicator library</h2><p>Documentation-only addresses and reserved example domains</p></div><Badge tone="teal">4 INDICATORS</Badge></div><div className="filterbar"><div className="filter-input"><Search size={16} /><input aria-label="Search indicators" placeholder="Search an IP, domain, or URL…" value={query} onChange={e => setQuery(e.target.value)} /></div><select aria-label="Indicator type" value={type} onChange={e => setType(e.target.value)}>{['All types', 'IPv4', 'Domain', 'URL'].map(t => <option key={t}>{t}</option>)}</select></div><Table columns={[{ key: 'value', label: 'INDICATOR', render: r => <span className="mono">{r.value}</span> }, { key: 'type', label: 'TYPE' }, { key: 'risk', label: 'SEVERITY', render: r => <Badge>{r.risk}</Badge> }, { key: 'source', label: 'SOURCE' }, { key: 'matches', label: 'CORRELATIONS' }]} rows={indicators.filter(i => i.value.includes(query.toLowerCase()) && (type === 'All types' || i.type === type))} /></Card>; }
function IntelligencePage() { return <><Card className="padded intelligence-intro"><span className="eyebrow">INTELLIGENCE COVERAGE</span><h2>Connect evidence to a wider context.</h2><p>Provider adapters will enrich extracted indicators with reputation, attribution, and related campaigns. No external providers are connected.</p></Card><div className="feature-row">{[['Reputation feeds', 'Domain, URL, and file reputation', 'Indicators → Reputation → Confidence'], ['Detection rules', 'YARA signature matching', 'Static files → Rules → Findings'], ['Campaign intelligence', 'Relationships and attribution', 'Indicators → Relationships → Context']].map(([title, text, flow]) => <Card className="padded" key={title}><Badge tone="neutral">NOT CONNECTED</Badge><h3>{title}</h3><p>{text}</p><div className="flow-label">{flow}</div></Card>)}</div></>; }
function CorrelationPage() { return <div className="module-grid"><Card className="padded"><h2>Sample evidence chain</h2><p className="muted">How independent findings may support an investigation.</p><div className="pipeline">{[['01', 'finance-update.apk', 'Sample package · APK analysis'], ['02', 'Sensitive permission request', 'Manifest signal · Medium'], ['03', '198.51.100.24', 'Extracted indicator · Documentation address'], ['04', 'Credential harvesting pattern', 'Illustrative signature · Critical']].map(([n, title, text]) => <div key={n}><span>{n}</span><section><h3>{title}</h3><p>{text}</p></section></div>)}</div></Card><Card className="padded"><h2>Risk scoring model</h2><p>Future scoring will combine severity, confidence, and relationships. No risk engine runs in Step 1.</p>{[['Static findings', '40%'], ['Indicator reputation', '30%'], ['Behavioral patterns in code', '20%'], ['Context and confidence', '10%']].map(([label, score]) => <div className="detail-line" key={label}><span>{label}</span><Badge tone="neutral">{score}</Badge></div>)}<div className="info-note">Illustrative weighting only. The scoring model will be validated in a later step.</div></Card></div>; }
function EndpointsPage() { return <Card className="padded"><div className="panel-heading flush"><div><h2>Endpoint coverage</h2><p>Endpoint integrations are not part of the foundation release.</p></div><Badge tone="neutral">0 CONNECTED</Badge></div><div className="state"><Server size={38} /><h3>No endpoints connected</h3><p>A future read-only connector will bring endpoint security signals into this workspace.</p><Button disabled>Connector planned</Button></div><div className="info-note">The current application does not install agents, monitor devices, or collect endpoint telemetry.</div></Card>; }
function SettingsPage() { const { session } = useAuth(); const [compact, setCompact] = useState(() => localStorage.getItem('cyberintel.compact') === 'true'); const [saved, setSaved] = useState(false); function save() { localStorage.setItem('cyberintel.compact', String(compact)); document.documentElement.classList.toggle('compact', compact); setSaved(true); } return <div className="module-grid"><Card className="padded"><h2>Workspace preferences</h2><p className="muted">Preferences are saved on this device.</p><label className="setting-row"><span><strong>Compact tables</strong><small>Reduce row spacing in event and indicator tables.</small></span><input type="checkbox" checked={compact} onChange={e => { setCompact(e.target.checked); setSaved(false); }} /></label><Button onClick={save}>{saved ? <><Check size={16} />Preferences saved</> : 'Save preferences'}</Button>{saved && <span className="sr-only" role="status">Preferences saved on this device.</span>}</Card><Card className="padded"><h2>Account & connection</h2>{[['Name', session.user.name], ['Email', session.user.email], ['Role', session.user.role], ['Authentication', session.demo ? 'Local development demo' : 'JWT / Spring Boot'], ['API endpoint', api.defaults.baseURL], ['Analysis tools', 'Not connected']].map(([label, value]) => <div className="detail-line" key={label}><span>{label}</span><strong>{value}</strong></div>)}</Card></div>; }
